# ------------ Builder -------------
FROM node:18-alpine AS builder
WORKDIR /app

# Copiar package.json y lock
COPY package*.json ./

# Instalar dependencias y compilar
RUN npm install --production && npm run build

# ------------ Runtime -------------
FROM nginx:1.25-alpine AS runtime
# Copiar configuración mínima de nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# El contenedor expone el puerto 80 por defecto
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]