version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: rentauber
      POSTGRES_USER: renta_user
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: renta-uber-backend/Dockerfile
    restart: unless-stopped
    environment:
      PORT: 3001
      JWT_SECRET: renta-uber-secret-key-2024
      JWT_REFRESH_SECRET: renta-uber-refresh-secret-2024
      DATABASE_URL: postgres://renta_user:secret@db:5432/rentauber
    depends_on:
      - db
    ports:
      - "3001:3001"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: "http://localhost:3001/api"
    environment:
      - VITE_API_URL=http://backend:3001/api
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data: